## Задача 1

Скачать данные по ссылке https://www.kaggle.com/datasets/ionaskel/laptop-prices  
Считать данные с помощью pandas  
Вывести на экран первые 5 строк

In [1]:
import pandas as pd
df = pd.read_csv('kc_house_data.csv')
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180.0,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170.0,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770.0,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050.0,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680.0,0,1987,0,98074,47.6168,-122.045,1800,7503

### 1.2 Создать новый признак delta_renovated, который будет содержать разницу в годах между годом реновацией дома и годом постройки дома
Если реновации дома не было, то в новом признаке поставьте 0

In [2]:
df["delta_renovated"] = (df["yr_renovated"] - df["yr_built"]).apply(lambda x: x if x > 0 else 0)
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,delta_renovated
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,1180.0,0,1955,0,98178,47.5112,-122.257,1340,5650,0
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,2170.0,400,1951,1991,98125,47.7210,-122.319,1690,7639,40
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,770.0,0,1933,0,98028,47.7379,-122.233,2720,8062,0
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,1050.0,910,1965,0,98136,47.5208,-122.393,1360,5000,0
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,1680.0,0,1987,0,98074,47.6168,-122.045,1800,7503,0

In [3]:
df[['yr_built', 'yr_renovated', 'delta_renovated']].head()

   yr_built  yr_renovated  delta_renovated
0      1955             0                0
1      1951          1991               40
2      1933             0                0
3      1965             0                0
4      1987             0                0

### 1.3 Создайте признаки года продажи, месяца продажи

In [8]:
df['year_sale'] = df['date'].apply(lambda x: x[:4])
df['month_sale'] = df['date'].apply(lambda x: x[4:6])
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,delta_renovated,year_sale,month_sale
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,1955,0,98178,47.5112,-122.257,1340,5650,0,2014,10
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,1951,1991,98125,47.7210,-122.319,1690,7639,40,2014,12
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,1933,0,98028,47.7379,-122.233,2720,8062,0,2015,02
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,1965,0,98136,47.5208,-122.393,1360,5000,0,2014,12
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,1987,0,98074,47.6168,-122.045,1800,7503,0,2015,02

In [9]:
df[['date', 'year_sale', 'month_sale']].head()

              date year_sale month_sale
0  20141013T000000      2014         10
1  20141209T000000      2014         12
2  20150225T000000      2015         02
3  20141209T000000      2014         12
4  20150218T000000      2015         02

### 1.4 Удалите признаки date, zipcode, lat, long

In [10]:
df.drop(columns=['date', 'zipcode', "lat", "long"], inplace=True)
df.head()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,sqft_living15,sqft_lot15,delta_renovated,year_sale,month_sale
0,7129300520,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180.0,0,1955,0,1340,5650,0,2014,10
1,6414100192,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170.0,400,1951,1991,1690,7639,40,2014,12
2,5631500400,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770.0,0,1933,0,2720,8062,0,2015,02
3,2487200875,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050.0,910,1965,0,1360,5000,0,2014,12
4,1954400510,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680.0,0,1987,0,1800,7503,0,2015,02

## Задача 2

Создайте датафрейм с клиентами:  
clients = pd.DataFrame({'client_id': [1459, 4684, 3498, 3942, 4535, 2308, 2866, 2765, 1472, 4236, 2295, 939, 3840, 280, 20, 4332, 3475, 4213, 3113, 4809, 2134, 2242, 2068, 4929, 1384, 1589, 3317, 2260, 1727, 1764, 1611, 1474], 'house_id': [8965450190, 6823100225, 5104540330, 2131701075, 1522700060, 1189000207, 6821600300, 7137950720, 9510920050, 6131600255, 5428000070, 1788800910, 8100400160, 3123049142, 6306800010, 5083000375, 7920100025, 1951600150, 809001400, 339600110, 1622049154, 1099600250, 8563000110, 2768100205, 3995700435, 8861700030, 3303980210, 7731100066, 8146100580, 825069097, 3889100029, 9524100196]})

In [12]:
clients = pd.DataFrame({
    'client_id': [1459, 4684, 3498, 3942, 4535, 2308, 2866, 2765, 1472, 4236,
                  2295, 939,  3840, 280,  20,   4332, 3475, 4213, 3113, 4809,
                  2134, 2242, 2068, 4929, 1384, 1589, 3317, 2260, 1727, 1764,
                  1611, 1474],
    'house_id': [8965450190, 6823100225, 5104540330, 2131701075, 1522700060, 1189000207, 6821600300, 7137950720, 9510920050, 6131600255,
                 5428000070, 1788800910, 8100400160, 3123049142, 6306800010, 5083000375, 7920100025, 1951600150, 809001400,  339600110,
                 1622049154, 1099600250, 8563000110, 2768100205, 3995700435, 8861700030, 3303980210, 7731100066, 8146100580, 825069097,
                 3889100029, 9524100196]})
clients.head()

   client_id    house_id
0       1459  8965450190
1       4684  6823100225
2       3498  5104540330
3       3942  2131701075
4       4535  1522700060

### 2.1 Присоедините к таблице clients данные по домам через метод join

In [13]:
clients_id = clients.set_index('house_id')
df_id = df.set_index('id')
clients_id.join(df_id).reset_index().head()

,index,client_id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,sqft_living15,sqft_lot15,delta_renovated,year_sale,month_sale
0,339600110,4809,395000.0,3,2.50,1610,3755,2.0,0,0,...,7,1610.0,0,1987,0,1300,3823,0,2014,09
1,809001400,3113,925000.0,3,1.00,1630,3200,1.5,0,0,...,8,1630.0,0,1912,0,1710,3600,0,2014,09
2,825069097,1764,770000.0,3,2.50,2650,40705,2.0,0,0,...,9,2650.0,0,1994,0,2550,42625,0,2014,06
3,1099600250,2242,260000.0,3,1.75,1710,6400,1.0,0,0,...,7,1240.0,470,1976,0,1600,6400,0,2014,12
4,1189000207,2308,387000.0,2,2.50,1170,1394,2.0,0,0,...,8,1170.0,0,2001,0,1250,3136,0,2014,10

### 2.2 Присоедините к таблице clients данные по домам через метод merge
Это нужно, чтобы понимать, какие дома покупались клиентами  
house_id - это индексы датафрейма с домами

In [14]:
merged = clients.merge(df, left_on='house_id', right_on='id')
merged.head()

,client_id,house_id,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,sqft_living15,sqft_lot15,delta_renovated,year_sale,month_sale
0,1459,8965450190,8965450190,295000.0,3,2.50,1500,3060,2.0,0,...,7,1500.0,0,1994,0,2700,7734,0,2015,02
1,4684,6823100225,6823100225,700000.0,4,1.75,1870,6000,1.0,0,...,8,1670.0,200,1949,0,1710,6000,0,2015,04
2,3498,5104540330,5104540330,679000.0,4,2.50,3680,7236,2.0,0,...,10,3680.0,0,2006,0,3310,7180,0,2015,05
3,3942,2131701075,2131701075,420000.0,3,1.75,1720,5000,1.5,0,...,8,1720.0,0,1932,2009,1410,8300,77,2014,12
4,4535,1522700060,1522700060,518000.0,4,2.75,2520,14021,2.0,0,...,9,2520.0,0,1999,0,2330,14007,0,2014,06

## Задача 3
Составьте несколько сводных таблиц

### 3.1 Найдите среднюю стоимость домов в зависимости от количества спален
Отсортируйте от меньшей стоимости к большей

In [ ]:
df.groupby('bedrooms').agg({'price': 'mean'}).sort_values('price')

                 price
bedrooms
1         3.176429e+05
2         4.013727e+05
0         4.095038e+05
3         4.662321e+05
11        5.200000e+05
4         6.354195e+05
33        6.400000e+05
5         7.865998e+05
10        8.193333e+05
6         8.255206e+05
9         8.939998e+05
7         9.511847e+05
8         1.105077e+06

### 3.2 Найдите минимальную, среднюю и максимальную стоимости домов в зависимости от состояния дома

In [ ]:
df.groupby('condition').agg({'price': ['min', 'mean', 'max']})

              price
                min           mean        max
condition
1           78000.0  334431.666667  1500000.0
2           80000.0  327287.145349  2555000.0
3           75000.0  542012.578148  7062500.0
4           89000.0  521200.390033  7700000.0
5          110000.0  612418.089359  3650000.0

### 3.3 Постройте таблицу с подсчетом количества домов в данных в зависимости от вида на набережную и оценкой вида

In [ ]:
df.pivot_table(index='waterfront',
               columns='view',
               values='id',
               aggfunc='count',
               fill_value=0)

view            0    1    2    3    4
waterfront
0           19489  331  955  491  184
1               0    1    8   19  135

### 3.4 Каких домов в зависимости от этажности и количества спален больше?

In [15]:
pd.crosstab(index=df['floors'],
            columns=df['bedrooms'])

bedrooms  0    1     2     3     4    5    6   7   8   9   10  11  33
floors
1.0        4  162  1951  5455  2383  605  104   9   5   0   1   0   1
1.5        0   21   182   786   698  185   30   7   1   0   0   0   0
2.0        6   12   497  3118  3682  775  119  19   6   4   2   1   0
2.5        0    1     5    56    58   23   14   2   0   2   0   0   0
3.0        2    3   123   405    61   13    5   1   0   0   0   0   0
3.5        1    0     2     4     0    0    0   0   1   0   0   0   0

### 3.5 Постройте таблицу с подсчетом медианной стоимости домов в данных в зависимости от состояния дома и оценки дома

In [ ]:
df.pivot_table(index='condition',
               columns='grade',
               values='price',
               aggfunc='median',
               fill_value=0)

grade,1,3,4,5,6,7,8,9,10,11,12,13
condition,,,,,,,,,,,,
1,142000,0,150000,190000,255000,403500,932500,0,0,0,0,0
2,0,280000,145000,180000,235000,305000,429000,715000,1752500,0,0,0
3,0,75000,205000,234475,265000,357500,485000,689000,890000,1209500,1807500,2888000
4,0,0,238525,229975,295000,390000,571250,823500,1030000,1685000,2125000,5750000
5,0,262000,0,227450,285475,456000,696000,1078000,1650000,2050000,1990000,0